openapi: 3.0.1
info:
  title: API Bsale Shop.
  description: Esta API se encarga del manejo de la Base de Datos sobre la empresa Bsale shop.
  version: 1.0.0
servers:
  - url: https://bsale-app-js.herokuapp.com/api/v1/
  
tags:
  - name: Categorys
    description: Categoria de los productos

  - name: Products
    description: Productos 
paths:
  /categorys:
    get:
      tags:
        - Categorys
      description: Permite optener todas las categorias que se encuentran en la api
      parameters:
      - in: query
        name: id
        required: false
        type: int
        description: IDentificacion de la Categoria
        schema:
          type: int
          example: 2
      - in: query
        name: name
        required: false
        type: string
        description: Nombre de la Categoria
        schema:
          type: string
          example: pisco
          
      - in: body
        description: Ejemplo
        schema:
          type: object
          properties:
            id:
              type: int
              description: id de categoria
              example: '2'
            nombre:
              type: string
              description: primer nombre
              example: 'pisco'

  /categorys/:id:
    get:
      tags:
        - Categorys
      description: Obtiene la categoria por el Id
      parameters:
      - in: query
        name: id
        required: false
        type: int
        description: IDentificacion de la Categoria
        schema:
          type: int
          example: 1
      - in: query
        name: name
        required: false
        description: Nombre de la Categoria
        schema:
          type: string
          example: bebida energetica
        
      - in: body
        description: Ejemplo    
        schema:     
          type: object
          properties:
            id:
              type: int
              description: id de categoria
              example: '1'
            nombre:
              type: string
              description: segundo nodsdmbre
              example: 'bebida energetica'  

  paths:
  /products:
    get:
      tags:
        - Products
      description: Permite obtener todos los productos de la API
      parameters:
      - in: query
        name: id
        required: false
        type: int
        description: IDentificacion del producto
        schema:
          type: int
          example: 10
      - in: query
        name: name
        required: false
        type: string
        description: Nombre del producto
        schema:
          type: string
          example: PISCO ARTESANOS 35ยบ
      - in: query
        name: url_image
        required: false
        type: string
        description: URL de la imagen
        schema:
          type: string
          example: https://dojiw2m9tvv09.cloudfront.net/11132/product/artesanos8818.jpg
      - in: query
        name: price
        required: false
        type: int
        description: Precio del Producto
        schema:
          type: float
          example: 3990
      - in: query
        name: discount
        required: false
        type: int
        description: Descuento del Producto
        schema:
          type: int
          example: 0
      - in: query
        name: category
        required: false
        type: int
        description: Categoria del Producto
        schema:
          type: int
          example: 2
      - in: body
        description: Ejemplo    
        schema:     
          type: object
          properties:
            id:
              type: int
              description: id de categoria
              example: '10'
            nombre:
              type: string
              description: Nombre del  Producto
              example: 'PISCO ARTESANOS 35ยบ' 
            url_image:
              type: string
              description: URL del  Producto
              example: 'https://dojiw2m9tvv09.cloudfront.net/11132/product/artesanos8818.jpg' 
            price:
              type: int
              description: Precio del Producto
              example: '3990'
            discount:
              type: int
              description: Descuento del Producto
              example: '0'
            category:
              type: int
              description: Categoria del Producto
              example: '2'

  /products/:id:
    get:
      tags:
        - Products
      description: Permite obtener el ID de el Producto que contiene la API
      parameters:
      - in: query
        name: id
        required: false
        type: int
        description: IDentificacion del producto
        schema:
          type: int
          example: 140
      - in: query
        name: name
        required: false
        type: string
        description: Nombre del producto
        schema:
          type: string
          example: ABSOLUT
      - in: query
        name: url_image
        required: false
        type: string
        description: URL de la imagen
        schema:
          type: string
          example: https://dojiw2m9tvv09.cloudfront.net/11132/product/absolut21381.png
      - in: query
        name: price
        required: false
        type: int
        description: Precio del Producto
        schema:
          type: float
          example: 8990
      - in: query
        name: discount
        required: false
        type: int
        description: Descuento del Producto
        schema:
          type: int
          example: 30
      - in: query
        name: category
        required: false
        type: int
        description: Categoria del Producto
        schema:
          type: int
          example: 7
      - in: body
        description: Ejemplo    
        schema:     
          type: object
          properties:
            id:
              type: int
              description: id de categoria
              example: '104'
            nombre:
              type: string
              description: Nombre del  Producto
              example: 'ABSOLUT' 
            url_image:
              type: string
              description: URL del  Producto
              example: 'https://dojiw2m9tvv09.cloudfront.net/11132/product/absolut21381.png' 
            price:
              type: int
              description: Precio del Producto
              example: '8990'
            discount:
              type: int
              description: Descuento del Producto
              example: '30'
            category:
              type: int
              description: Categoria del Producto
              example: '7'
            
           
