openapi: 3.0.1
info:
  title: API Bsale Shop.
  description: Esta API se encarga del manejo de la Base de Datos sobre la empresa
    Bsale shop.
  version: 1.0.0
servers:
- url: https://bsale-app-js.herokuapp.com/api/v1/
tags:
- name: Categorys
  description: Categoria de los productos
- name: Products
  description: Productos
paths:
  /categorys:
    get:
      tags:
      - Categorys
      description: Permite optener todas las categorias que se encuentran en la api
      operationId: categorysGET
      parameters:
      - name: id
        in: query
        description: IDentificacion de la Categoria
        required: false
        style: form
        explode: true
        schema:
          type: int
          example: 2
      - name: name
        in: query
        description: Nombre de la Categoria
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: pisco
      x-swagger-router-controller: Categorys
  /categorys/:id:
    get:
      tags:
      - Categorys
      description: Obtiene la categoria por el Id
      operationId: categorysidGET
      parameters:
      - name: id
        in: query
        description: IDentificacion de la Categoria
        required: false
        style: form
        explode: true
        schema:
          type: int
          example: 1
      - name: name
        in: query
        description: Nombre de la Categoria
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: bebida energetica
      x-swagger-router-controller: Categorys
  /products:
    get:
      tags:
      - Products
      description: Permite obtener todos los productos de la API
      operationId: productsGET
      parameters:
      - name: id
        in: query
        description: IDentificacion del producto
        required: false
        style: form
        explode: true
        schema:
          type: int
          example: 10
      - name: name
        in: query
        description: Nombre del producto
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: PISCO ARTESANOS 35ยบ
      - name: url_image
        in: query
        description: URL de la imagen
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: https://dojiw2m9tvv09.cloudfront.net/11132/product/artesanos8818.jpg
      - name: price
        in: query
        description: Precio del Producto
        required: false
        style: form
        explode: true
        schema:
          type: float
          example: 3990
      - name: discount
        in: query
        description: Descuento del Producto
        required: false
        style: form
        explode: true
        schema:
          type: int
          example: 0
      - name: category
        in: query
        description: Categoria del Producto
        required: false
        style: form
        explode: true
        schema:
          type: int
          example: 2
      x-swagger-router-controller: Products
  /products/:id:
    get:
      tags:
      - Products
      description: Permite obtener el ID de el Producto que contiene la API
      operationId: productsidGET
      parameters:
      - name: id
        in: query
        description: IDentificacion del producto
        required: false
        style: form
        explode: true
        schema:
          type: int
          example: 140
      - name: name
        in: query
        description: Nombre del producto
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: ABSOLUT
      - name: url_image
        in: query
        description: URL de la imagen
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: https://dojiw2m9tvv09.cloudfront.net/11132/product/absolut21381.png
      - name: price
        in: query
        description: Precio del Producto
        required: false
        style: form
        explode: true
        schema:
          type: float
          example: 8990
      - name: discount
        in: query
        description: Descuento del Producto
        required: false
        style: form
        explode: true
        schema:
          type: int
          example: 30
      - name: category
        in: query
        description: Categoria del Producto
        required: false
        style: form
        explode: true
        schema:
          type: int
          example: 7
      x-swagger-router-controller: Products
components: {}
